/*
 * Refresh data from baseData seeds.
 * Base seeds now already use the normalized numeric format, so this script
 * simply copies them into /data and recomputes tag articleCount for safety.
 */

const fs = require('fs');
const path = require('path');
const basePaths = {
  tags: path.join(__dirname, '../baseData/mockTags.js'),
  articles: path.join(__dirname, '../baseData/mockArticles.js'),
  feeds: path.join(__dirname, '../baseData/mockFeeds.js'),
  users: path.join(__dirname, '../baseData/mockUsers.js'),
  highlights: path.join(__dirname, '../baseData/mockHighlights.js')
};
const dataPaths = {
  tags: path.join(__dirname, '../data/mockTags.js'),
  articles: path.join(__dirname, '../data/mockArticles.js'),
  feeds: path.join(__dirname, '../data/mockFeeds.js'),
  users: path.join(__dirname, '../data/mockUsers.js'),
  highlights: path.join(__dirname, '../data/mockHighlights.js')
};

function loadModule(p) {
  delete require.cache[require.resolve(p)];
  return require(p);
}

function serialize(name, varName, data) {
  return `/**\n * Auto-generated by refreshDataFromBase.js (${name})\n * DO NOT EDIT MANUALLY - regenerate from baseData.\n */\n\nconst ${varName} = ${JSON.stringify(data, null, 2)};\n\nmodule.exports = { ${varName} };\n`;
}

function recomputeTagCounts(tags, articles) {
  const countMap = new Map();
  for (const a of articles) {
    for (const tid of (a.tags || [])) {
      countMap.set(tid, (countMap.get(tid) || 0) + 1);
    }
  }
  return tags.map(t => ({ ...t, articleCount: countMap.get(t.id) || 0 }));
}

function main() {
  // Load base seeds
  const { mockUsers: baseUsers } = loadModule(basePaths.users);
  const { mockFeeds: baseFeeds } = loadModule(basePaths.feeds);
  const { mockArticles: baseArticles } = loadModule(basePaths.articles);
  const { mockHighlights: baseHighlights } = loadModule(basePaths.highlights);
  const { mockTags: baseTags } = loadModule(basePaths.tags);

  // Seeds already normalized; shallow clone for safety.
  const users = baseUsers.map(u => ({ ...u }));
  const feeds = baseFeeds.map(f => ({ ...f }));
  const articles = baseArticles.map(a => ({ ...a }));
  const highlights = baseHighlights.map(h => ({ ...h }));
  const tagsWithCounts = recomputeTagCounts(baseTags.map(t => ({ ...t })), articles).sort((a, b) => a.id - b.id);

  // Write out files
  fs.writeFileSync(dataPaths.users, serialize('users', 'mockUsers', users), 'utf8');
  fs.writeFileSync(dataPaths.feeds, serialize('feeds', 'mockFeeds', feeds), 'utf8');
  fs.writeFileSync(dataPaths.articles, serialize('articles', 'mockArticles', articles), 'utf8');
  fs.writeFileSync(dataPaths.highlights, serialize('highlights', 'mockHighlights', highlights), 'utf8');
  fs.writeFileSync(dataPaths.tags, serialize('tags', 'mockTags', tagsWithCounts), 'utf8');

  console.log(`Refreshed data sets: users(${users.length}) feeds(${feeds.length}) articles(${articles.length}) highlights(${highlights.length}) tags(${tagsWithCounts.length}).`);
}

if (require.main === module) {
  main();
}

module.exports = { main };
